#!/bin/python2
import glob, os, time, shutil, sys
import urllib2, json, base64

DOWNLOAD_PATH="/home/fx/auto-hevc/sources/"
MIN_FREE_SPACE=512

class Torrent:
    def __init__(self, torrent_file):
        if len(sys.argv) == 2:
            self.gid = self.method('aria2.addTorrent', base64.b64encode(open(torrent_file).read()) )
            self.method('aria2.pause', self.gid)
            self.file = '1'
            self.method('select-file', self.file)
            self.files = str(len(self.method('aria2.getFiles', self.gid)))
            self.save_state()
        else:
            self.load_state()
            self.method('select-file', self.file)

        self.name = self.method('aria2.tellStatus', self.gid)['bittorrent']['info']['name']
        self.file_path = self.method('aria2.getFiles', self.gid)[int(self.file) - 1]['path']
        self.file_name = os.path.basename(self.method('aria2.getFiles', self.gid)[int(self.file) - 1]['path'])
        self.length = ''
        self.done = ''
        self.status = 'null'
        self.refresh_status()

    def save_state(self):
        state = open('torrent.state', 'w')
        self.files = str(len(self.method('aria2.getFiles', self.gid)))
        state.write(':'.join([self.gid, self.files, self.file]) + "\n\n")
        for i in range(int(self.files)):
            file_name = os.path.basename(self.method('aria2.getFiles', self.gid)[i]['path'])
            state.write('%02d' % (i + 1) + ": " + file_name + "\n")
        state.close()

    def load_state(self):
        state = open('torrent.state', 'r').readlines()[0].strip().split(':')
        self.gid = state[0]
        self.files = state[1]
        self.file = state[2]

    def method(self, *args):
        if args[0] == 'select-file':
            jsonreq = json.dumps({'jsonrpc':'2.0', 'id':'qwer', 'method':'aria2.changeOption', 'params':[self.gid, {'select-file':args[1]}]})
        else:
            jsonreq = json.dumps({'jsonrpc':'2.0', 'id':'asdf', 'method':args[0], 'params':[args[1]]})
        server = urllib2.urlopen('http://localhost:6800/jsonrpc', jsonreq)
        return json.loads(server.read())['result']

    def next(self):
        self.file = str(int(self.file) + 1)
        self.method('select-file', self.file)
        self.length = self.method('aria2.getFiles', self.gid)[int(self.file) - 1]['length']
        self.file_path = self.method('aria2.getFiles', self.gid)[int(self.file) - 1]['path']
        self.file_name = os.path.basename(self.method('aria2.getFiles', self.gid)[int(self.file) - 1]['path'])
        self.save_state()

    def refresh_status(self):
        prev_status = self.status
        while self.status == prev_status:
            self.status = self.method('aria2.tellStatus', self.gid)['status']
            time.sleep(1)


def check_free():
    free_space = os.statvfs(DOWNLOAD_PATH)[1] * os.statvfs(DOWNLOAD_PATH)[4]

    if free_space < MIN_FREE_SPACE * 1048576:
        print("[  PAUSE  ] Low disk space. Available: " + str(free_space / 1048576) + " MB")
        torrent.method('aria2.pause', torrent.gid)

        while free_space < MIN_FREE_SPACE * 1048576:
            time.sleep(10)
            free_space = os.statvfs(DOWNLOAD_PATH)[1] * os.statvfs(DOWNLOAD_PATH)[4]

        print("[ UNPAUSE ] Freed disk space. Available: " + str(free_space / 1048576) + " MB")
        torrent.method('aria2.unpause', torrent.gid)


def advance_queue():
    time.sleep(30)

    if torrent.file == torrent.files:
        print("[   END   ] " + torrent.name)
        os.remove('torrent.state')
        sys.exit()

    shutil.move(torrent.file_path, download_path)
    dirlist = glob.glob(os.path.dirname(torrent.file_path) + "/*")

    for f in dirlist:
        if os.path.isfile(f):
            os.remove(f)
        else:
            shutil.rmtree(f)

    torrent.next()
    print("[ current ] " + os.path.basename(torrent.method('aria2.getFiles', torrent.gid)[int(torrent.file) - 1]['path']))


def start_queue():
    print("[  BEGIN  ] " + torrent.name)
    torrent.load_state()

    if torrent.status != 'active':
        time.sleep(30)
        torrent.method('aria2.unpause', torrent.gid)
        torrent.refresh_status()

    torrent.length = torrent.method('aria2.getFiles', torrent.gid)[int(torrent.file) - 1]['length']
    print("[ current ] " + torrent.file_name)

    while True:
        torrent.done = torrent.method('aria2.getFiles', torrent.gid)[int(torrent.file) - 1]['completedLength']
        if torrent.done == torrent.length:
            advance_queue()
        check_free()
        time.sleep(30)


def main():
    global torrent
    if len(sys.argv) == 2:
        torrent = Torrent(sys.argv[1])
    else:
        torrent = Torrent('')
    start_queue()


main()

